In [10]:
import pandas as pd

df = pd.read_excel("ejercicio1.xlsx")
df.head()

     Sabor  Tamaño Hielo  Calificacion
0  Naranja   Chica    Si           8.5
1  Naranja   Chica    No           7.0
2  Naranja  Grande    Si           9.0
3  Naranja  Grande    No           7.5
4     Coco   Chica    Si           7.5

Ahora cambiaremos en Tamaño y Hielos los valores a 1,0

In [49]:
df["Tamaño"] = df["Tamaño"].replace({"Chica": 0, "Grande": 1})
df["Hielo"] = df["Hielo"].replace({"No": 0, "Si": 1})
df.head()

,Sabor,Tamaño,Hielo,Calificacion,Naranja,Coco,Kahlua,Fresa-Piña,Sandia
0,Naranja,False,False,8.5,True,False,False,False,False
1,Naranja,False,False,7.0,True,False,False,False,False
2,Naranja,False,False,9.0,True,False,False,False,False
3,Naranja,False,False,7.5,True,False,False,False,False
4,Coco,False,False,7.5,False,True,False,False,False

In [54]:
df = pd.read_excel("ejercicio1.xlsx")
df["Naranja"] = df["Sabor"] == "Naranja"
df["Coco"] = df["Sabor"] == "Coco"
df["Kahlua"] = df["Sabor"] == "Kahlua"
df["Fresa-Piña"] = df["Sabor"] == "Fresa-Piña"
df["Sandia"] = df["Sabor"] == "Sandia"
df["Tamaño"] = (df["Tamaño"] == "Grande").astype(int)
df["Hielo"] = (df["Hielo"] == "Si").astype(int)

df[["Naranja","Coco","Kahlua","Fresa-Piña","Sandia", "Tamaño", "Hielo", "Calificacion"]].head()

   Naranja   Coco  Kahlua  Fresa-Piña  Sandia  Tamaño  Hielo  Calificacion
0     True  False   False       False   False       0      1           8.5
1     True  False   False       False   False       0      0           7.0
2     True  False   False       False   False       1      1           9.0
3     True  False   False       False   False       1      0           7.5
4    False   True   False       False   False       0      1           7.5

In [41]:
import statsmodels.api as sm
X = df[["Naranja", "Coco", "Kahlua", "Fresa-Piña", "Sandia", "Tamaño", "Hielo"]]
Y = df["Calificacion"]
ols = sm.OLS(Y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:           Calificacion   R-squared:                       0.927
Model:                            OLS   Adj. R-squared:                  0.894
Method:                 Least Squares   F-statistic:                     27.67
Date:                Thu, 03 Sep 2026   Prob (F-statistic):           1.11e-06
Time:                        17:14:11   Log-Likelihood:                -6.3060
No. Observations:                  20   AIC:                             26.61
Df Residuals:                      13   BIC:                             33.58
Df Model:                           6
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Naranja        6.9500      0.243     28.557      0.000       6.424       7.476
Coco           6.0750      0.243     24.962      0.000       5.549       6.601
Kahlua         7.8250      0.243     32.152      0.000       7.299       8.351
Fresa-Piña     6.5750      0.243     27.016      0.000       6.049       7.101
Sandia         5.3250      0.243     21.880      0.000       4.799       5.851
Tamaño         0.5000      0.184      2.718      0.018       0.103       0.897
Hielo          1.6000      0.184      8.697      0.000       1.203       1.997
==============================================================================
Omnibus:                       15.683   Durbin-Watson:                   2.372
Prob(Omnibus):                  0.000   Jarque-Bera (JB):               15.836
Skew:                          -1.542   Prob(JB):                     0.000364
Kurtosis:                       6.081   Cond. No.                         4.00
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [57]:
from sklearn.preprocessing import OrdinalEncoder

enc = OrdinalEncoder()
enc.fit(df[["Tamaño", "Hielo"]])
enc.categories_

[array(['Chica', 'Grande'], dtype=object), array(['No', 'Si'], dtype=object)]

In [60]:
df = pd.read_excel("ejercicio1.xlsx")
df[["Tamaño", "Hielo"]] = enc.transform(df[["Tamaño", "Hielo"]])
enc_sabor = OrdinalEncoder()
df[["Sabor"]] = enc_sabor.fit_transform(df[["Sabor"]])
df.head()

   Sabor  Tamaño  Hielo  Calificacion
0    3.0     0.0    1.0           8.5
1    3.0     0.0    0.0           7.0
2    3.0     1.0    1.0           9.0
3    3.0     1.0    0.0           7.5
4    0.0     0.0    1.0           7.5

In [61]:
X = df[["Sabor", "Tamaño", "Hielo"]]
Y = df["Calificacion"]
ols = sm.OLS(Y, X)
results = ols.fit()
results.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                                 OLS Regression Results
=======================================================================================
Dep. Variable:           Calificacion   R-squared (uncentered):                   0.832
Model:                            OLS   Adj. R-squared (uncentered):              0.802
Method:                 Least Squares   F-statistic:                              28.03
Date:                Thu, 03 Sep 2026   Prob (F-statistic):                    8.29e-07
Time:                        17:45:19   Log-Likelihood:                         -51.372
No. Observations:                  20   AIC:                                      108.7
Df Residuals:                      17   BIC:                                      111.7
Df Model:                           3
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Sabor          1.2425      0.419      2.963      0.009       0.358       2.127
Tamaño         3.2100      1.370      2.344      0.032       0.320       6.100
Hielo          4.3100      1.370      3.147      0.006       1.420       7.200
==============================================================================
Omnibus:                        0.282   Durbin-Watson:                   1.242
Prob(Omnibus):                  0.869   Jarque-Bera (JB):                0.373
Skew:                          -0.236   Prob(JB):                        0.830
Kurtosis:                       2.527   Cond. No.                         5.04
==============================================================================

Notes:
[1] R² is computed without centering (uncentered) since the model does not contain a constant.
[2] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""